name: bridge_webview_flutter
description: A Flutter plugin that provides a BridgeWebView widget on Android and iOS.
version: 0.1.4
homepage: https://github.com/epoll-j/bridge_webview_flutter

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
      ios:
        pluginClass: FLTWebViewFlutterPlugin
